os: osx
osx_image: xcode12.3
language: objective-c

env:
  global:
    - OPENSSL="1.1.1g"	# https://www.openssl.org/source/
    - LIBCURL="7.71.1"	# https://curl.haxx.se/download.html
    - NGHTTP2="1.41.0"	# https://nghttp2.org/
    - EXAMPLE="example/iOS Test App"
    - PATH=/Users/travis/Library/Python/3.9/bin:$PATH   # for AWS

before_install:
  # set up awscli packages
  - python3 -m pip install pyopenssl
  - python3 -m pip install --user awscli
  - ls /Users/travis/Library/Python/
  - ls /Users/travis/Library/Python/3.9/bin
  - aws s3 ls jasonacox.com.travis-build-stage-storage

stages:
  - nghttp2
  - opensslphase1
  - opensslphase2
  - libcurl
  - test

jobs:
  include:
    - stage: nghttp2
      script:
        - cd nghttp2;./nghttp2-build.sh -v "$NGHTTP2"
        - cd ..
        - tar -zcf "nghttp2.tgz" nghttp2/Catalyst nghttp2/iOS* nghttp2/tvOS nghttp2/lib 
        - aws s3 cp "nghttp2.tgz" s3://jasonacox.com.travis-build-stage-storage/
        - aws s3 ls jasonacox.com.travis-build-stage-storage

    - stage: opensslphase1
      script: 
        - cd openssl;./openssl-build-phase1.sh -v "$OPENSSL"
        - cd ..
        - cp /tmp/openssl openssl/Mac
        - /tmp/openssl version
        - tar -zcf "openssl-1.tgz" openssl/Mac openssl/Catalyst openssl/iOS* openssl/tvOS
        - aws s3 cp "openssl-1.tgz" s3://jasonacox.com.travis-build-stage-storage/
        - aws s3 ls jasonacox.com.travis-build-stage-storage

    - stage: opensslphase2
      script: 
        - cd openssl;./openssl-build-phase2.sh -v "$OPENSSL"
        - cd ..
        - tar -zcf "openssl-2.tgz" openssl/Mac openssl/Catalyst openssl/iOS* openssl/tvOS
        - aws s3 cp "openssl-2.tgz" s3://jasonacox.com.travis-build-stage-storage/
        - aws s3 ls jasonacox.com.travis-build-stage-storage

    - stage: libcurl
      script: 
        - echo "Fetching openssl and nghttp2 libraries..."
        - aws s3 cp s3://jasonacox.com.travis-build-stage-storage/openssl-1.tgz .
        - aws s3 cp s3://jasonacox.com.travis-build-stage-storage/openssl-2.tgz .
        - aws s3 cp s3://jasonacox.com.travis-build-stage-storage/nghttp2.tgz .
        - tar -zxf openssl-1.tgz
        - tar -zxf openssl-2.tgz
        - tar -zxf nghttp2.tgz
        - cd curl;./libcurl-build.sh -v "$LIBCURL"
        - cd ..
        - cp /tmp/curl curl/lib
        - /tmp/curl -V
        - echo "Uploading libcurl libraries..."
        - tar -zcf "curl.tgz" curl/lib curl/include
        - aws s3 cp "curl.tgz" s3://jasonacox.com.travis-build-stage-storage/
        - aws s3 ls jasonacox.com.travis-build-stage-storage

    - stage: test
      script:
        - echo "Fetching libcurl, openssl and nghttp2 libraries..."
        - aws s3 cp s3://jasonacox.com.travis-build-stage-storage/curl.tgz .
        - aws s3 cp s3://jasonacox.com.travis-build-stage-storage/openssl-1.tgz .
        - aws s3 cp s3://jasonacox.com.travis-build-stage-storage/openssl-2.tgz .
        - aws s3 cp s3://jasonacox.com.travis-build-stage-storage/nghttp2.tgz .
        - tar -zxf openssl-1.tgz
        - tar -zxf openssl-2.tgz
        - tar -zxf nghttp2.tgz
        - tar -zxf curl.tgz
        - echo "Fetching root certs..."
        - curl -s https://curl.haxx.se/ca/cacert.pem > "$EXAMPLE/cacert.pem"
        - echo "Copying libraries to Test App ..."
        - mkdir -p "$EXAMPLE/libs/"
        - cp openssl/iOS-fat/lib/libcrypto.a "$EXAMPLE/libs/libcrypto.a"
        - cp openssl/iOS-fat/lib/libssl.a "$EXAMPLE/libs/libssl.a"
        - cp openssl/iOS-fat/include/openssl/* "$EXAMPLE/include/openssl/"
        - cp curl/include/curl/* "$EXAMPLE/include/curl/"
        - cp curl/lib/libcurl_iOS-fat.a "$EXAMPLE/libs/libcurl.a"
        - cp nghttp2/lib/libnghttp2_iOS-fat.a "$EXAMPLE/libs/libnghttp2.a"
        - echo "Building iOS Test App..."
        - xcodebuild clean -project "$EXAMPLE/iOS Test App.xcodeproj"
        - xcodebuild build -project "$EXAMPLE/iOS Test App.xcodeproj" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
